% ------------------------------------------------------------------------------
% Write a KML file header.
%
% SYNTAX :
%   ge_put_header1(a_fId, a_fileDescription, a_fileName)
%
% INPUT PARAMETERS :
%   a_fId             : KML file Id
%   a_fileDescription : file description
%   a_fileName        : file name
%
% OUTPUT PARAMETERS :
%
% EXAMPLES :
%
% SEE ALSO : 
% AUTHORS  : Jean-Philippe Rannou (Altran)(jean-philippe.rannou@altran.com)
% ------------------------------------------------------------------------------
% RELEASES :
%   04/19/2015 - RNU - creation
% ------------------------------------------------------------------------------
function ge_put_header1(a_fId, a_fileDescription, a_fileName)

% GPS locations in red
gpsPosColor = ge_rgb_2_hex([1, 0, 0]);
% GPS trajectory in red
gpsTrajColor = ge_rgb_2_hex([1, 0, 0]);
% sub-surface trajectory: SURF_DRIFT
subTrajSurfDriftColor = ge_rgb_2_hex([1, 255, 1]/255);
% sub-surface trajectory: DESCENT
subTrajDescentColor = ge_rgb_2_hex([102, 204, 204]/255);
% sub-surface trajectory: SUBSURF_DRIFT
subTrajSubDriftColor = ge_rgb_2_hex([51, 255, 255]/255);
% sub-surface trajectory: SUBSURF_INFLEXION
subTrajInflexionColor = ge_rgb_2_hex([255, 51, 255]/255);
% sub-surface trajectory: SUBSURF_ASCENT
subTrajAscentColor = ge_rgb_2_hex([255, 102, 102]/255);
% sub-surface trajectory: SUBSURF_GROUNDED
subTrajGroundedColor = ge_rgb_2_hex([0, 0, 0]/255);
% sub-surface trajectory: SUBSURF_INCONSISTANT
subTrajInconsistentColor = ge_rgb_2_hex([1, 0, 0]);


header = [ ...
   '<?xml version="1.0" encoding="UTF-8"?>', 10, ...
   '<kml xmlns="http://earth.google.com/kml/2.1">', 10, ...
   '<Document>', 10, ...
   9, '<description><![CDATA[', a_fileDescription, ']]></description>', 10, ...
   9, '<open>1</open>', 10, ...
   9, '<name>', a_fileName, '</name>', 10, ...
   9, '<Style id="GPS_POS">', 10, ...
   9, 9, '<IconStyle>', 10, ...
   9, 9, 9, '<color>', ['FF' gpsPosColor], '</color>', 10, ...
   9, 9, 9, '<Icon>', 10, ...
   9, 9, 9, 9, '<href>http://maps.google.com/mapfiles/kml/shapes/shaded_dot.png</href>', 10, ...
   9, 9, 9, '</Icon>', 10, ...
   9, 9, '</IconStyle>', 10, ...
   9, 9, '<LabelStyle>', 10, ...
   9, 9, 9, '<scale>0.6</scale>', 10, ...
   9, 9, '</LabelStyle>', 10, ...
   9, '</Style>', 10, ...
   9, '<Style id="GPS_TRAJ">', 10, ...
   9, 9, '<LineStyle>', 10, ...
   9, 9, 9, '<color>', ['ff' gpsTrajColor], '</color>', 10, ...
   9, 9, 9, '<width>3</width>', 10, ...
   9, 9, '</LineStyle>', 10, ...
   9, '</Style>', 10, ...
   9, '<Style id="SUB_TRAJ_MEAS_0">', 10, ...
   9, 9, '<IconStyle>', 10, ...
   9, 9, 9, '<color>', ['FF' subTrajSurfDriftColor], '</color>', 10, ...
   9, 9, 9, '<Icon>', 10, ...
   9, 9, 9, 9, '<href>http://maps.google.com/mapfiles/kml/paddle/wht-blank.png</href>', 10, ...
   9, 9, 9, '</Icon>', 10, ...
   9, 9, '</IconStyle>', 10, ...
   9, 9, '<LabelStyle>', 10, ...
   9, 9, 9, '<scale>0.6</scale>', 10, ...
   9, 9, '</LabelStyle>', 10, ...
   9, '</Style>', 10, ...
   9, '<Style id="SUB_TRAJ_MEAS_1">', 10, ...
   9, 9, '<IconStyle>', 10, ...
   9, 9, 9, '<color>', ['FF' subTrajDescentColor], '</color>', 10, ...
   9, 9, 9, '<Icon>', 10, ...
   9, 9, 9, 9, '<href>http://maps.google.com/mapfiles/kml/paddle/wht-blank.png</href>', 10, ...
   9, 9, 9, '</Icon>', 10, ...
   9, 9, '</IconStyle>', 10, ...
   9, 9, '<LabelStyle>', 10, ...
   9, 9, 9, '<scale>0.6</scale>', 10, ...
   9, 9, '</LabelStyle>', 10, ...
   9, '</Style>', 10, ...
   9, '<Style id="SUB_TRAJ_MEAS_2">', 10, ...
   9, 9, '<IconStyle>', 10, ...
   9, 9, 9, '<color>', ['FF' subTrajSubDriftColor], '</color>', 10, ...
   9, 9, 9, '<Icon>', 10, ...
   9, 9, 9, 9, '<href>http://maps.google.com/mapfiles/kml/paddle/wht-blank.png</href>', 10, ...
   9, 9, 9, '</Icon>', 10, ...
   9, 9, '</IconStyle>', 10, ...
   9, 9, '<LabelStyle>', 10, ...
   9, 9, 9, '<scale>0.6</scale>', 10, ...
   9, 9, '</LabelStyle>', 10, ...
   9, '</Style>', 10, ...
   9, '<Style id="SUB_TRAJ_MEAS_3">', 10, ...
   9, 9, '<IconStyle>', 10, ...
   9, 9, 9, '<color>', ['FF' subTrajInflexionColor], '</color>', 10, ...
   9, 9, 9, '<Icon>', 10, ...
   9, 9, 9, 9, '<href>http://maps.google.com/mapfiles/kml/paddle/wht-blank.png</href>', 10, ...
   9, 9, 9, '</Icon>', 10, ...
   9, 9, '</IconStyle>', 10, ...
   9, 9, '<LabelStyle>', 10, ...
   9, 9, 9, '<scale>0.6</scale>', 10, ...
   9, 9, '</LabelStyle>', 10, ...
   9, '</Style>', 10, ...
   9, '<Style id="SUB_TRAJ_MEAS_4">', 10, ...
   9, 9, '<IconStyle>', 10, ...
   9, 9, 9, '<color>', ['FF' subTrajAscentColor], '</color>', 10, ...
   9, 9, 9, '<Icon>', 10, ...
   9, 9, 9, 9, '<href>http://maps.google.com/mapfiles/kml/paddle/wht-blank.png</href>', 10, ...
   9, 9, 9, '</Icon>', 10, ...
   9, 9, '</IconStyle>', 10, ...
   9, 9, '<LabelStyle>', 10, ...
   9, 9, 9, '<scale>0.6</scale>', 10, ...
   9, 9, '</LabelStyle>', 10, ...
   9, '</Style>', 10, ...
   9, '<Style id="SUB_TRAJ_MEAS_5">', 10, ...
   9, 9, '<IconStyle>', 10, ...
   9, 9, 9, '<color>', ['FF' subTrajGroundedColor], '</color>', 10, ...
   9, 9, 9, '<Icon>', 10, ...
   9, 9, 9, 9, '<href>http://maps.google.com/mapfiles/kml/paddle/wht-blank.png</href>', 10, ...
   9, 9, 9, '</Icon>', 10, ...
   9, 9, '</IconStyle>', 10, ...
   9, 9, '<LabelStyle>', 10, ...
   9, 9, 9, '<scale>0.6</scale>', 10, ...
   9, 9, '</LabelStyle>', 10, ...
   9, '</Style>', 10, ...
   9, '<Style id="SUB_TRAJ_MEAS_6">', 10, ...
   9, 9, '<IconStyle>', 10, ...
   9, 9, 9, '<color>', ['FF' subTrajInconsistentColor], '</color>', 10, ...
   9, 9, 9, '<Icon>', 10, ...
   9, 9, 9, 9, '<href>http://maps.google.com/mapfiles/kml/paddle/wht-blank.png</href>', 10, ...
   9, 9, 9, '</Icon>', 10, ...
   9, 9, '</IconStyle>', 10, ...
   9, 9, '<LabelStyle>', 10, ...
   9, 9, 9, '<scale>0.6</scale>', 10, ...
   9, 9, '</LabelStyle>', 10, ...
   9, '</Style>', 10, ...
   9, '<Style id="PROF_DESC_POS">', 10, ...
   9, 9, '<IconStyle>', 10, ...
   9, 9, 9, '<color>', ['FF' subTrajDescentColor], '</color>', 10, ...
   9, 9, 9, '<Icon>', 10, ...
   9, 9, 9, 9, '<href>http://maps.google.com/mapfiles/kml/pushpin/wht-pushpin.png</href>', 10, ...
   9, 9, 9, '</Icon>', 10, ...
   9, 9, '</IconStyle>', 10, ...
   9, 9, '<LabelStyle>', 10, ...
   9, 9, 9, '<scale>0.6</scale>', 10, ...
   9, 9, '</LabelStyle>', 10, ...
   9, '</Style>', 10, ...
   9, '<Style id="PROF_ASC_POS">', 10, ...
   9, 9, '<IconStyle>', 10, ...
   9, 9, 9, '<color>', ['FF' subTrajAscentColor], '</color>', 10, ...
   9, 9, 9, '<Icon>', 10, ...
   9, 9, 9, 9, '<href>http://maps.google.com/mapfiles/kml/pushpin/wht-pushpin.png</href>', 10, ...
   9, 9, 9, '</Icon>', 10, ...
   9, 9, '</IconStyle>', 10, ...
   9, 9, '<LabelStyle>', 10, ...
   9, 9, 9, '<scale>0.6</scale>', 10, ...
   9, 9, '</LabelStyle>', 10, ...
   9, '</Style>', 10, ...
   9, '<Style id="SUB_TRAJ_0">', 10, ...
   9, 9, '<LineStyle>', 10, ...
   9, 9, 9, '<color>', ['ff' subTrajSurfDriftColor], '</color>', 10, ...
   9, 9, 9, '<width>3</width>', 10, ...
   9, 9, '</LineStyle>', 10, ...
   9, '</Style>', 10, ...
   9, '<Style id="SUB_TRAJ_1">', 10, ...
   9, 9, '<LineStyle>', 10, ...
   9, 9, 9, '<color>', ['ff' subTrajDescentColor], '</color>', 10, ...
   9, 9, 9, '<width>3</width>', 10, ...
   9, 9, '</LineStyle>', 10, ...
   9, '</Style>', 10, ...
   9, '<Style id="SUB_TRAJ_2">', 10, ...
   9, 9, '<LineStyle>', 10, ...
   9, 9, 9, '<color>', ['ff' subTrajSubDriftColor], '</color>', 10, ...
   9, 9, 9, '<width>3</width>', 10, ...
   9, 9, '</LineStyle>', 10, ...
   9, '</Style>', 10, ...
   9, '<Style id="SUB_TRAJ_3">', 10, ...
   9, 9, '<LineStyle>', 10, ...
   9, 9, 9, '<color>', ['ff' subTrajInflexionColor], '</color>', 10, ...
   9, 9, 9, '<width>3</width>', 10, ...
   9, 9, '</LineStyle>', 10, ...
   9, '</Style>', 10, ...
   9, '<Style id="SUB_TRAJ_4">', 10, ...
   9, 9, '<LineStyle>', 10, ...
   9, 9, 9, '<color>', ['ff' subTrajAscentColor], '</color>', 10, ...
   9, 9, 9, '<width>3</width>', 10, ...
   9, 9, '</LineStyle>', 10, ...
   9, '</Style>', 10, ...
   9, '<Style id="SUB_TRAJ_5">', 10, ...
   9, 9, '<LineStyle>', 10, ...
   9, 9, 9, '<color>', ['ff' subTrajGroundedColor], '</color>', 10, ...
   9, 9, 9, '<width>3</width>', 10, ...
   9, 9, '</LineStyle>', 10, ...
   9, '</Style>', 10, ...
   9, '<Style id="SUB_TRAJ_6">', 10, ...
   9, 9, '<LineStyle>', 10, ...
   9, 9, 9, '<color>', ['ff' subTrajInconsistentColor], '</color>', 10, ...
   9, 9, 9, '<width>3</width>', 10, ...
   9, 9, '</LineStyle>', 10, ...
   9, '</Style>', 10 ...
   ];

fprintf(a_fId, '%s', header);

return
