% ------------------------------------------------------------------------------
% Get the basic structure to store a profile information.
%
% SYNTAX :
%  [o_profStruct] = gl_get_profile_init_struct
%
% INPUT PARAMETERS :
%
% OUTPUT PARAMETERS :
%   o_profStruct : profile initialized structure
%
% EXAMPLES :
%
% SEE ALSO : 
% AUTHORS  : Jean-Philippe Rannou (Altran)(jean-philippe.rannou@altran.com)
% ------------------------------------------------------------------------------
% RELEASES :
%   06/11/2013 - RNU - creation
% ------------------------------------------------------------------------------
function [o_profStruct] = gl_get_profile_init_struct

% global default values
global g_decGl_dateDef;
global g_decGl_ncDateDef;
global g_decGl_ncArgosLonDef;
global g_decGl_ncArgosLatDef;

% output parameters initialization
o_profStruct = struct( ...
   'cycleNumber', -1, ...
   'decodedProfileNumber', -1, ...
   'profileNumber', -1, ...
   'primarySamplingProfileFlag', 1, ...
   'phaseNumber', -1, ...
   'direction', ' ', ...
   'date', g_decGl_ncDateDef, ...
   'dateQc', '', ...
   'locationDate', g_decGl_ncDateDef, ...
   'locationLon', g_decGl_ncArgosLonDef, ...
   'locationLat', g_decGl_ncArgosLatDef, ...
   'locationQc', ' ', ...
   'posSystem', ' ', ...
   'vertSamplingScheme', ' ', ...
   'paramList', '', ...
   'paramDataMode', '', ...
   'paramNumberWithSubLevels', '', ... % position, in the paramList of the parameters with a sublevel
   'paramNumberOfSubLevels', '', ... % number of sublevels for the concerned parameter
   'data', '', ...
   'dataQc', '', ...
   'dataAdj', '', ...
   'dataAdjQc', '', ...
   'dateList', '', ...
   'dates', '', ...
   'minMeasDate', g_decGl_dateDef, ...
   'maxMeasDate', g_decGl_dateDef, ...
   'testDoneList', '', ...
   'testFailedList', '', ...
   'projectName', '', ...
   'piName', '', ...
   'floatSerialNo', '', ...
   'firmwareVersion', '');

return
