% ------------------------------------------------------------------------------
% Get EGO variable attributes from EGO variable name.
%
% SYNTAX :
%  [o_egoVarStruct] = gl_get_ego_var_attributes(a_egoVarName)
%
% INPUT PARAMETERS :
%   a_egoVarName : name of the EGO variable
%
% OUTPUT PARAMETERS :
%   o_egoVarStruct : EGO variable associated attributes
%
% EXAMPLES :
%
% SEE ALSO :
% AUTHORS  : Jean-Philippe Rannou (Altran)(jean-philippe.rannou@altran.com)
% ------------------------------------------------------------------------------
% RELEASES :
%   06/15/2015 - RNU - creation
%   02/20/2018 - RNU - updated from 16/01/2018 version of the list
% ------------------------------------------------------------------------------
function [o_egoVarStruct] = gl_get_ego_var_attributes(a_egoVarName)

% output parameters initialization
o_egoVarStruct = [];

egoVarName = a_egoVarName;
again = 1;
while (again ~= 0)
   
   switch (egoVarName)
      
      %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
      % COORDINATE VARIABLES
      
      case 'TIME'
         o_egoVarStruct = struct( ...
            'ego_variable_name', 'TIME', ...
            'dim', 'TIME', ...
            'typeof', 'double', ...
            'long_name', 'Epoch time', ...
            'standard_name', 'time', ...
            'units', 'seconds since 1970-01-01T00:00:00Z', ...
            'FillValue', double(9999999999), ...
            'valid_min', double(0), ...
            'valid_max', double(90000), ...
            'axis', 'T', ...
            'ancillary_variable', 'TIME_QC', ...
            'sdn_parameter_urn', 'SDN:P01::ELTMEP01', ...
            'sdn_uom_urn', 'SDN:P06::UTBB' ...
            );
         
      case 'JULD'
         o_egoVarStruct = struct( ...
            'ego_variable_name', 'JULD', ...
            'dim', 'TIME', ...
            'typeof', 'double', ...
            'long_name', 'Julian 1950 time', ...
            'standard_name', 'time', ...
            'units', 'days since 1950-01-01T00:00:00Z', ...
            'FillValue', double(999999), ...
            'valid_min', double(0), ...
            'valid_max', double(90000), ...
            'axis', 'T', ...
            'ancillary_variable', 'JULD_QC', ...
            'sdn_parameter_urn', 'SDN:P01::XXX', ...
            'sdn_uom_urn', 'SDN:P06::UTAA' ...
            );
         
      case 'LATITUDE'
         o_egoVarStruct = struct( ...
            'ego_variable_name', 'LATITUDE', ...
            'dim', 'TIME', ...
            'typeof', 'double', ...
            'long_name', 'Measurement latitude', ...
            'standard_name', 'latitude', ...
            'units', 'degree_north', ...
            'FillValue', double(99999), ...
            'valid_min', double(-90), ...
            'valid_max', double(90), ...
            'axis', 'Y', ...
            'ancillary_variable', 'POSITION_QC', ...
            'reference', 'WGS84', ...
            'coordinate_reference_frame', 'urn:ogc:crs:EPSG::4326', ...
            'sdn_parameter_urn', 'SDN:P01::ALATZZ01', ...
            'sdn_uom_urn', 'SDN:P06::DEGN' ...
            );
         
      case 'LONGITUDE'
         o_egoVarStruct = struct( ...
            'ego_variable_name', 'LONGITUDE', ...
            'dim', 'TIME', ...
            'typeof', 'double', ...
            'long_name', 'Measurement longitude', ...
            'standard_name', 'longitude', ...
            'units', 'degree_east', ...
            'FillValue', double(99999), ...
            'valid_min', double(-180), ...
            'valid_max', double(180), ...
            'axis', 'X', ...
            'ancillary_variable', 'POSITION_QC', ...
            'reference', 'WGS84', ...
            'coordinate_reference_frame', 'urn:ogc:crs:EPSG::4326', ...
            'sdn_parameter_urn', 'SDN:P01::ALONZZ01', ...
            'sdn_uom_urn', 'SDN:P06::DEGE' ...
            );
         
      case 'TIME_GPS'
         o_egoVarStruct = struct( ...
            'ego_variable_name', 'TIME_GPS', ...
            'dim', 'TIME_GPS', ...
            'typeof', 'double', ...
            'long_name', 'Epoch time of the GPS fixes', ...
            'standard_name', 'time', ...
            'units', 'seconds since 1970-01-01T00:00:00Z', ...
            'FillValue', double(9999999999), ...
            'valid_min', double(0), ...
            'valid_max', double(90000), ...
            'axis', 'T', ...
            'ancillary_variable', 'TIME_GPS_QC', ...
            'sdn_parameter_urn', 'SDN:P01::ELTMEP01', ...
            'sdn_uom_urn', 'SDN:P06::UTBB' ...
            );
         
      case 'LATITUDE_GPS'
         o_egoVarStruct = struct( ...
            'ego_variable_name', 'LATITUDE_GPS', ...
            'dim', 'TIME_GPS', ...
            'typeof', 'double', ...
            'long_name', 'Gps fixed latitude', ...
            'standard_name', 'latitude', ...
            'units', 'degree_north', ...
            'FillValue', double(99999), ...
            'valid_min', double(-90), ...
            'valid_max', double(90), ...
            'axis', 'Y', ...
            'ancillary_variable', 'POSITION_GPS_QC', ...
            'reference', 'WGS84', ...
            'coordinate_reference_frame', 'urn:ogc:crs:EPSG::4326', ...
            'sdn_parameter_urn', 'SDN:P01::ALATZZ01', ...
            'sdn_uom_urn', 'SDN:P06::DEGN' ...
            );
         
      case 'LONGITUDE_GPS'
         o_egoVarStruct = struct( ...
            'ego_variable_name', 'LONGITUDE_GPS', ...
            'dim', 'TIME_GPS', ...
            'typeof', 'double', ...
            'long_name', 'Gps fixed longitude', ...
            'standard_name', 'longitude', ...
            'units', 'degree_east', ...
            'FillValue', double(99999), ...
            'valid_min', double(-180), ...
            'valid_max', double(180), ...
            'axis', 'X', ...
            'ancillary_variable', 'POSITION_GPS_QC', ...
            'reference', 'WGS84', ...
            'coordinate_reference_frame', 'urn:ogc:crs:EPSG::4326', ...
            'sdn_parameter_urn', 'SDN:P01::ALONZZ01', ...
            'sdn_uom_urn', 'SDN:P06::DEGE' ...
            );
         
         %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
         % C PARAMETERS
         
      case 'CNDC'
         o_egoVarStruct = struct( ...
            'ego_variable_name', 'CNDC', ...
            'dim', 'TIME', ...
            'typeof', 'float', ...
            'standard_name', 'sea_water_electrical_conductivity', ...
            'units', 'mhos/m', ...
            'FillValue', single(99999), ...
            'long_name', 'Electrical conductivity', ...
            'valid_min', single(0), ...
            'valid_max', single(8.5), ...
            'ancillary_variable', 'CNDC_QC', ...
            'sdn_parameter_urn', 'SDN:P01::CNDCST01', ...
            'sdn_uom_urn', 'SDN:P06::UECA', ...
            'sdn_uom_name', '' ...
            );         

      case 'PRES'
         o_egoVarStruct = struct( ...
            'ego_variable_name', 'PRES', ...
            'dim', 'TIME', ...
            'typeof', 'float', ...
            'standard_name', 'sea_water_pressure', ...
            'units', 'decibar', ...
            'FillValue', single(99999), ...
            'axis', 'Z', ...
            'positive', 'down', ...
            'long_name', 'Sea water pressure, equals 0 at sea-level', ...
            'valid_min', single(0), ...
            'valid_max', single(12000), ...
            'ancillary_variable', 'PRES_QC', ...
            'sdn_parameter_urn', 'SDN:P01::PRESPR01', ...
            'sdn_uom_urn', 'SDN:P06::UPDB', ...
            'sdn_uom_name', '' ...
            );
         
      case 'TEMP'
         o_egoVarStruct = struct( ...
            'ego_variable_name', 'TEMP', ...
            'dim', 'TIME', ...
            'typeof', 'float', ...
            'standard_name', 'sea_water_temperature', ...
            'units', 'degree_Celsius', ...
            'FillValue', single(99999), ...
            'long_name', 'Sea temperature in-situ ITS-90 scale', ...
            'valid_min', single(-2.5), ...
            'valid_max', single(40), ...
            'ancillary_variable', 'TEMP_QC', ...
            'sdn_parameter_urn', 'SDN:P01::TEMPST01', ...
            'sdn_uom_urn', 'SDN:P06::UPAA', ...
            'sdn_uom_name', '' ...
            );

      case 'PSAL'
         o_egoVarStruct = struct( ...
            'ego_variable_name', 'PSAL', ...
            'dim', 'TIME', ...
            'typeof', 'float', ...
            'standard_name', 'sea_water_salinity', ...
            'units', 'psu', ...
            'FillValue', single(99999), ...
            'long_name', 'Practical salinity', ...
            'valid_min', single(2), ...
            'valid_max', single(41), ...
            'ancillary_variable', 'PSAL_QC', ...
            'sdn_parameter_urn', 'SDN:P01::PSALST01', ...
            'sdn_uom_urn', 'SDN:P06::UUUU', ...
            'sdn_uom_name', '' ...
            );
         
         %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
         % B PARAMETERS
         
      case 'DOXY'
         o_egoVarStruct = struct( ...
            'ego_variable_name', 'DOXY', ...
            'dim', 'TIME', ...
            'typeof', 'float', ...
            'standard_name', 'moles_of_oxygen_per_unit_mass_in_sea_water', ...
            'units', 'micromole/kg', ...
            'FillValue', single(99999), ...
            'long_name', 'Dissolved oxygen', ...
            'valid_min', single(-5), ...
            'valid_max', single(600), ...
            'ancillary_variable', 'DOXY_QC', ...
            'sdn_parameter_urn', 'SDN:P01::DOXMZZXX', ...
            'sdn_uom_urn', 'SDN:P06::KGUM', ...
            'sdn_uom_name', '' ...
            );
         
      case 'BBP470'
         o_egoVarStruct = struct( ...
            'ego_variable_name', 'BBP470', ...
            'dim', 'TIME', ...
            'typeof', 'float', ...
            'standard_name', '', ...
            'units', 'm-1', ...
            'FillValue', single(99999), ...
            'long_name', 'Particle backscattering at 470 nanometers', ...
            'valid_min', '', ...
            'valid_max', '', ...
            'ancillary_variable', 'BBP470_QC', ...
            'sdn_parameter_urn', 'SDN:P01::BB117B01', ...
            'sdn_uom_urn', 'SDN:P06::PMSR', ...
            'sdn_uom_name', '' ...
            );         
         
      case 'BBP532'
         o_egoVarStruct = struct( ...
            'ego_variable_name', 'BBP532', ...
            'dim', 'TIME', ...
            'typeof', 'float', ...
            'standard_name', '', ...
            'units', 'm-1', ...
            'FillValue', single(99999), ...
            'long_name', 'Particle backscattering at 532 nanometers', ...
            'valid_min', '', ...
            'valid_max', '', ...
            'ancillary_variable', 'BBP532_QC', ...
            'sdn_parameter_urn', 'SDN:P01::BB117G01', ...
            'sdn_uom_urn', 'SDN:P06::PMSR', ...
            'sdn_uom_name', '' ...
            );
         
      case 'BBP650' % for gliders only
         o_egoVarStruct = struct( ...
            'ego_variable_name', 'BBP650', ...
            'dim', 'TIME', ...
            'typeof', 'float', ...
            'standard_name', '', ...
            'units', 'm-1', ...
            'FillValue', single(99999), ...
            'long_name', 'Particle backscattering at 650 nanometers', ...
            'valid_min', '', ...
            'valid_max', '', ...
            'ancillary_variable', 'BBP650_QC', ...
            'sdn_parameter_urn', 'SDN:P01::BB117R02', ...
            'sdn_uom_urn', 'SDN:P06::PMSR', ...
            'sdn_uom_name', '' ...
            );
                  
      case 'BBP700'
         o_egoVarStruct = struct( ...
            'ego_variable_name', 'BBP700', ...
            'dim', 'TIME', ...
            'typeof', 'float', ...
            'standard_name', '', ...
            'units', 'm-1', ...
            'FillValue', single(99999), ...
            'long_name', 'Particle backscattering at 700 nanometers', ...
            'valid_min', '', ...
            'valid_max', '', ...
            'ancillary_variable', 'BBP700_QC', ...
            'sdn_parameter_urn', 'SDN:P01::BB117NIR', ...
            'sdn_uom_urn', 'SDN:P06::PMSR', ...
            'sdn_uom_name', '' ...
            );
                  
      case 'BBP880' % for gliders only
         o_egoVarStruct = struct( ...
            'ego_variable_name', 'BBP880', ...
            'dim', 'TIME', ...
            'typeof', 'float', ...
            'standard_name', '', ...
            'units', 'm-1', ...
            'FillValue', single(99999), ...
            'long_name', 'Particle backscattering at 880 nanometers', ...
            'valid_min', '', ...
            'valid_max', '', ...
            'ancillary_variable', 'BBP880_QC', ...
            'sdn_parameter_urn', 'SDN:P01::BB117IIR', ...
            'sdn_uom_urn', 'SDN:P06::PMSR', ...
            'sdn_uom_name', '' ...
            );         
         
      case 'TURBIDITY'
         o_egoVarStruct = struct( ...
            'ego_variable_name', 'TURBIDITY', ...
            'dim', 'TIME', ...
            'typeof', 'float', ...
            'standard_name', 'sea_water_turbidity', ...
            'units', 'ntu', ...
            'FillValue', single(99999), ...
            'long_name', 'Sea water turbidity', ...
            'valid_min', '', ...
            'valid_max', '', ...
            'ancillary_variable', 'TURBIDITY_QC', ...
            'sdn_parameter_urn', 'SDN:P01::TURBXXXX', ...
            'sdn_uom_urn', 'SDN:P06::USTU', ...
            'sdn_uom_name', '' ...
            );         
         
      case 'CP660'
         o_egoVarStruct = struct( ...
            'ego_variable_name', 'CP660', ...
            'dim', 'TIME', ...
            'typeof', 'float', ...
            'standard_name', '', ...
            'units', 'm-1', ...
            'FillValue', single(99999), ...
            'long_name', 'Particle beam attenuation at 660 nanometers', ...
            'valid_min', '', ...
            'valid_max', '', ...
            'ancillary_variable', 'CP660_QC', ...
            'sdn_parameter_urn', 'SDN:P01::ATT650AC', ...
            'sdn_uom_urn', 'SDN:P06::UPRM', ...
            'sdn_uom_name', '' ...
            );           

      case 'CHLA'
         o_egoVarStruct = struct( ...
            'ego_variable_name', 'CHLA', ...
            'dim', 'TIME', ...
            'typeof', 'float', ...
            'standard_name', 'mass_concentration_of_chlorophyll_a_in_sea_water', ...
            'units', 'mg/m3', ...
            'FillValue', single(99999), ...
            'long_name', 'Chlorophyll-A', ...
            'valid_min', '', ...
            'valid_max', '', ...
            'ancillary_variable', 'CHLA_QC', ...
            'sdn_parameter_urn', 'SDN:P01::CPHLPR01', ...
            'sdn_uom_urn', 'SDN:P06::UMMC', ...
            'sdn_uom_name', '' ...
            );

      case 'CDOM'
         o_egoVarStruct = struct( ...
            'ego_variable_name', 'CDOM', ...
            'dim', 'TIME', ...
            'typeof', 'float', ...
            'standard_name', '', ...
            'units', 'ppb', ...
            'FillValue', single(99999), ...
            'long_name', 'Concentration of coloured dissolved organic matter in sea water', ...
            'valid_min', '', ...
            'valid_max', '', ...
            'ancillary_variable', 'CDOM_QC', ...
            'sdn_parameter_urn', 'SDN:P01::CDOMZZ01', ...
            'sdn_uom_urn', 'SDN:P06::UPPB', ...
            'sdn_uom_name', '' ...
            );
         
      case 'NITRATE'
         o_egoVarStruct = struct( ...
            'ego_variable_name', 'NITRATE', ...
            'dim', 'TIME', ...
            'typeof', 'float', ...
            'standard_name', 'moles_of_nitrate_per_unit_mass_in_sea_water', ...
            'units', 'micromole/kg', ...
            'FillValue', single(99999), ...
            'long_name', 'Nitrate', ...
            'valid_min', '', ...
            'valid_max', '', ...
            'ancillary_variable', 'NITRATE_QC', ...
            'sdn_parameter_urn', 'SDN:P01::MDMAP005', ...
            'sdn_uom_urn', 'SDN:P06::KGUM', ...
            'sdn_uom_name', '' ...
            );
         
      case 'BISULFIDE'
         o_egoVarStruct = struct( ...
            'ego_variable_name', 'BISULFIDE', ...
            'dim', 'TIME', ...
            'typeof', 'float', ...
            'standard_name', '', ...
            'units', 'micromole/kg', ...
            'FillValue', single(99999), ...
            'long_name', 'Bisulfide', ...
            'valid_min', '', ...
            'valid_max', '', ...
            'ancillary_variable', 'BISULFIDE_QC', ...
            'sdn_parameter_urn', 'SDN:P01::H2SXZZ01', ...
            'sdn_uom_urn', 'SDN:P06::KGUM', ...
            'sdn_uom_name', '' ...
            );
         
      case 'PH_IN_SITU_TOTAL'
         o_egoVarStruct = struct( ...
            'ego_variable_name', 'PH_IN_SITU_TOTAL', ...
            'dim', 'TIME', ...
            'typeof', 'float', ...
            'standard_name', 'sea_water_ph_reported_on_total_scale', ...
            'units', 'dimensionless', ...
            'FillValue', single(99999), ...
            'long_name', 'pH', ...
            'valid_min', '', ...
            'valid_max', '', ...
            'ancillary_variable', 'PH_IN_SITU_TOTAL_QC', ...
            'sdn_parameter_urn', 'SDN:P01::PHMASSXX', ...
            'sdn_uom_urn', 'SDN:P06::UUPH', ...
            'sdn_uom_name', '' ...
            );
         
      case 'DOWN_IRRADIANCE380'
         o_egoVarStruct = struct( ...
            'ego_variable_name', 'DOWN_IRRADIANCE380', ...
            'dim', 'TIME', ...
            'typeof', 'float', ...
            'standard_name', '', ...
            'units', 'W/m^2/nm', ...
            'FillValue', single(99999), ...
            'long_name', 'Downwelling irradiance at 380 nanometers', ...
            'valid_min', '', ...
            'valid_max', '', ...
            'ancillary_variable', 'DOWN_IRRADIANCE380_QC', ...
            'sdn_parameter_urn', 'SDN:P01::RXUD380E', ...
            'sdn_uom_urn', 'SDN:P06::UWNM', ...
            'sdn_uom_name', '' ...
            );
         
      case 'DOWN_IRRADIANCE412'
         o_egoVarStruct = struct( ...
            'ego_variable_name', 'DOWN_IRRADIANCE412', ...
            'dim', 'TIME', ...
            'typeof', 'float', ...
            'standard_name', '', ...
            'units', 'W/m^2/nm', ...
            'FillValue', single(99999), ...
            'long_name', 'Downwelling irradiance at 412 nanometers', ...
            'valid_min', '', ...
            'valid_max', '', ...
            'ancillary_variable', 'DOWN_IRRADIANCE412_QC', ...
            'sdn_parameter_urn', 'SDN:P01::RXUD412E', ...
            'sdn_uom_urn', 'SDN:P06::UWNM', ...
            'sdn_uom_name', '' ...
            );
         
      case 'DOWN_IRRADIANCE443'
         o_egoVarStruct = struct( ...
            'ego_variable_name', 'DOWN_IRRADIANCE443', ...
            'dim', 'TIME', ...
            'typeof', 'float', ...
            'standard_name', '', ...
            'units', 'W/m^2/nm', ...
            'FillValue', single(99999), ...
            'long_name', 'Downwelling irradiance at 443 nanometers', ...
            'valid_min', '', ...
            'valid_max', '', ...
            'ancillary_variable', 'DOWN_IRRADIANCE443_QC', ...
            'sdn_parameter_urn', 'SDN:P01::RXUD443E', ...
            'sdn_uom_urn', 'SDN:P06::UWNM', ...
            'sdn_uom_name', '' ...
            );
         
      case 'DOWN_IRRADIANCE490'
         o_egoVarStruct = struct( ...
            'ego_variable_name', 'DOWN_IRRADIANCE490', ...
            'dim', 'TIME', ...
            'typeof', 'float', ...
            'standard_name', '', ...
            'units', 'W/m^2/nm', ...
            'FillValue', single(99999), ...
            'long_name', 'Downwelling irradiance at 490 nanometers', ...
            'valid_min', '', ...
            'valid_max', '', ...
            'ancillary_variable', 'DOWN_IRRADIANCE490_QC', ...
            'sdn_parameter_urn', 'SDN:P01::RXUD490E', ...
            'sdn_uom_urn', 'SDN:P06::UWNM', ...
            'sdn_uom_name', '' ...
            );
         
      case 'DOWN_IRRADIANCE532'
         o_egoVarStruct = struct( ...
            'ego_variable_name', 'DOWN_IRRADIANCE532', ...
            'dim', 'TIME', ...
            'typeof', 'float', ...
            'standard_name', '', ...
            'units', 'W/m^2/nm', ...
            'FillValue', single(99999), ...
            'long_name', 'Downwelling irradiance at 532 nanometers', ...
            'valid_min', '', ...
            'valid_max', '', ...
            'ancillary_variable', 'DOWN_IRRADIANCE532_QC', ...
            'sdn_parameter_urn', 'SDN:P01::RXUD532E', ...
            'sdn_uom_urn', 'SDN:P06::UWNM', ...
            'sdn_uom_name', '' ...
            );
         
      case 'DOWN_IRRADIANCE555'
         o_egoVarStruct = struct( ...
            'ego_variable_name', 'DOWN_IRRADIANCE555', ...
            'dim', 'TIME', ...
            'typeof', 'float', ...
            'standard_name', '', ...
            'units', 'W/m^2/nm', ...
            'FillValue', single(99999), ...
            'long_name', 'Downwelling irradiance at 555 nanometers', ...
            'valid_min', '', ...
            'valid_max', '', ...
            'ancillary_variable', 'DOWN_IRRADIANCE555_QC', ...
            'sdn_parameter_urn', 'SDN:P01::RXUD555E', ...
            'sdn_uom_urn', 'SDN:P06::UWNM', ...
            'sdn_uom_name', '' ...
            );
         
      case 'UP_RADIANCE412'
         o_egoVarStruct = struct( ...
            'ego_variable_name', 'UP_RADIANCE412', ...
            'dim', 'TIME', ...
            'typeof', 'float', ...
            'standard_name', 'upwelling_radiance_in_sea_water', ...
            'units', 'W/m^2/nm/sr', ...
            'FillValue', single(99999), ...
            'long_name', 'Upwelling radiance at 412 nanometers', ...
            'valid_min', '', ...
            'valid_max', '', ...
            'ancillary_variable', 'UP_RADIANCE412_QC', ...
            'sdn_parameter_urn', 'SDN:P01::RXUU412L', ...
            'sdn_uom_urn', 'SDN:P06::UWNS', ...
            'sdn_uom_name', '' ...
            );

      case 'UP_RADIANCE443'
         o_egoVarStruct = struct( ...
            'ego_variable_name', 'UP_RADIANCE443', ...
            'dim', 'TIME', ...
            'typeof', 'float', ...
            'standard_name', 'upwelling_radiance_in_sea_water', ...
            'units', 'W/m^2/nm/sr', ...
            'FillValue', single(99999), ...
            'long_name', 'Upwelling radiance at 443 nanometers', ...
            'valid_min', '', ...
            'valid_max', '', ...
            'ancillary_variable', 'UP_RADIANCE443_QC', ...
            'sdn_parameter_urn', 'SDN:P01::RXUU443L', ...
            'sdn_uom_urn', 'SDN:P06::UWNS', ...
            'sdn_uom_name', '' ...
            );
         
      case 'UP_RADIANCE490'
         o_egoVarStruct = struct( ...
            'ego_variable_name', 'UP_RADIANCE490', ...
            'dim', 'TIME', ...
            'typeof', 'float', ...
            'standard_name', 'upwelling_radiance_in_sea_water', ...
            'units', 'W/m^2/nm/sr', ...
            'FillValue', single(99999), ...
            'long_name', 'Upwelling radiance at 490 nanometers', ...
            'valid_min', '', ...
            'valid_max', '', ...
            'ancillary_variable', 'UP_RADIANCE490_QC', ...
            'sdn_parameter_urn', 'SDN:P01::RXUU490L', ...
            'sdn_uom_urn', 'SDN:P06::UWNS', ...
            'sdn_uom_name', '' ...
            );
         
      case 'UP_RADIANCE555'
         o_egoVarStruct = struct( ...
            'ego_variable_name', 'UP_RADIANCE555', ...
            'dim', 'TIME', ...
            'typeof', 'float', ...
            'standard_name', 'upwelling_radiance_in_sea_water', ...
            'units', 'W/m^2/nm/sr', ...
            'FillValue', single(99999), ...
            'long_name', 'Upwelling radiance at 555 nanometers', ...
            'valid_min', '', ...
            'valid_max', '', ...
            'ancillary_variable', 'UP_RADIANCE555_QC', ...
            'sdn_parameter_urn', 'SDN:P01::RXUU555L', ...
            'sdn_uom_urn', 'SDN:P06::UWNS', ...
            'sdn_uom_name', '' ...
            );
         
      case 'DOWNWELLING_PAR'
         o_egoVarStruct = struct( ...
            'ego_variable_name', 'DOWNWELLING_PAR', ...
            'dim', 'TIME', ...
            'typeof', 'float', ...
            'standard_name', 'downwelling_photosynthetic_photon_flux_in_sea_water', ...
            'units', 'microMoleQuanta/m^2/sec', ...
            'FillValue', single(99999), ...
            'long_name', 'Downwelling photosynthetic available radiation', ...
            'valid_min', '', ...
            'valid_max', '', ...
            'ancillary_variable', 'DOWNWELLING_PAR_QC', ...
            'sdn_parameter_urn', 'SDN:P01::DWIRRXUD', ...
            'sdn_uom_urn', 'SDN:P06::UMES', ...
            'sdn_uom_name', '' ...
            );

      case 'URANINE'
         o_egoVarStruct = struct( ...
            'ego_variable_name', 'URANINE', ...
            'dim', 'TIME', ...
            'typeof', 'float', ...
            'standard_name', '', ...
            'units', 'ppb', ...
            'FillValue', single(99999), ...
            'long_name', 'Uranine', ...
            'valid_min', '', ...
            'valid_max', '', ...
            'ancillary_variable', 'URANINE_QC', ...
            'sdn_parameter_urn', '', ...
            'sdn_uom_urn', '', ...
            'sdn_uom_name', '' ...
            );

      case 'RHODAMINE'
         o_egoVarStruct = struct( ...
            'ego_variable_name', 'RHODAMINE', ...
            'dim', 'TIME', ...
            'typeof', 'float', ...
            'standard_name', '', ...
            'units', 'ppb', ...
            'FillValue', single(99999), ...
            'long_name', 'Rhodamine', ...
            'valid_min', '', ...
            'valid_max', '', ...
            'ancillary_variable', 'RHODAMINE_QC', ...
            'sdn_parameter_urn', '', ...
            'sdn_uom_urn', '', ...
            'sdn_uom_name', '' ...
            );

         %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
         % I PARAMETERS
         
      case 'TEMP_CNDC'
         o_egoVarStruct = struct( ...
            'ego_variable_name', 'TEMP_CNDC', ...
            'dim', 'TIME', ...
            'typeof', 'float', ...
            'standard_name', '', ...
            'units', 'degree_Celsius', ...
            'FillValue', single(99999), ...
            'long_name', 'Internal temperature of the conductivity cell', ...
            'valid_min', single(-2.0), ...
            'valid_max', single(40), ...
            'ancillary_variable', 'TEMP_CNDC_QC', ...
            'sdn_parameter_urn', '', ...
            'sdn_uom_urn', '', ...
            'sdn_uom_name', '' ...
            );

      case 'TEMP_DOXY'
         o_egoVarStruct = struct( ...
            'ego_variable_name', 'TEMP_DOXY', ...
            'dim', 'TIME', ...
            'typeof', 'float', ...
            'standard_name', 'temperature_of_sensor_for_oxygen_in_sea_water', ...
            'units', 'degree_Celsius', ...
            'FillValue', single(99999), ...
            'long_name', 'Sea temperature from oxygen sensor ITS-90 scale', ...
            'valid_min', single(-2.0), ...
            'valid_max', single(40), ...
            'ancillary_variable', 'TEMP_DOXY_QC', ...
            'sdn_parameter_urn', 'SDN:P01::OXYTAAOP', ...
            'sdn_uom_urn', 'SDN:P06::UPAA', ...
            'sdn_uom_name', '' ...
            );
         
      case 'TEMP_VOLTAGE_DOXY'
         o_egoVarStruct = struct( ...
            'ego_variable_name', 'TEMP_VOLTAGE_DOXY', ...
            'dim', 'TIME', ...
            'typeof', 'float', ...
            'standard_name', '', ...
            'units', 'volt', ...
            'FillValue', single(99999), ...
            'long_name', 'Thermistor voltage reported by oxygen sensor', ...
            'valid_min', '', ...
            'valid_max', '', ...
            'ancillary_variable', 'TEMP_VOLTAGE_DOXY_QC', ...
            'sdn_parameter_urn', 'SDN:P01::TCNTOPTT', ...
            'sdn_uom_urn', 'SDN:P06::UVLT', ...
            'sdn_uom_name', '' ...
            );
         
      case 'VOLTAGE_DOXY'
         o_egoVarStruct = struct( ...
            'ego_variable_name', 'VOLTAGE_DOXY', ...
            'dim', 'TIME', ...
            'typeof', 'float', ...
            'standard_name', '', ...
            'units', 'volt', ...
            'FillValue', single(99999), ...
            'long_name', 'Voltage reported by oxygen sensor', ...
            'valid_min', single(0), ...
            'valid_max', single(100), ...
            'ancillary_variable', 'VOLTAGE_DOXY_QC', ...
            'sdn_parameter_urn', 'SDN:P01::OXYOCPVL', ...
            'sdn_uom_urn', 'SDN:P06::UVLT', ...
            'sdn_uom_name', '' ...
            );
         
      case 'FREQUENCY_DOXY'
         o_egoVarStruct = struct( ...
            'ego_variable_name', 'FREQUENCY_DOXY', ...
            'dim', 'TIME', ...
            'typeof', 'float', ...
            'standard_name', '', ...
            'units', 'hertz', ...
            'FillValue', single(99999), ...
            'long_name', 'Frequency reported by oxygen sensor', ...
            'valid_min', single(0), ...
            'valid_max', single(25000), ...
            'ancillary_variable', 'FREQUENCY_DOXY_QC', ...
            'sdn_parameter_urn', 'SDN:P01::OXYOCPFR', ...
            'sdn_uom_urn', 'SDN:P06::UTHZ', ...
            'sdn_uom_name', '' ...
            );
         
      case 'COUNT_DOXY'
         o_egoVarStruct = struct( ...
            'ego_variable_name', 'COUNT_DOXY', ...
            'dim', 'TIME', ...
            'typeof', 'float', ...
            'standard_name', '', ...
            'units', 'count', ...
            'FillValue', single(99999), ...
            'long_name', 'Count reported by oxygen sensor', ...
            'valid_min', '', ...
            'valid_max', '', ...
            'ancillary_variable', 'COUNT_DOXY_QC', ...
            'sdn_parameter_urn', 'SDN:P01::OXYOOPCT', ...
            'sdn_uom_urn', 'SDN:P06::UUUU', ...
            'sdn_uom_name', '' ...
            );         
         
      case 'BPHASE_DOXY'
         o_egoVarStruct = struct( ...
            'ego_variable_name', 'BPHASE_DOXY', ...
            'dim', 'TIME', ...
            'typeof', 'float', ...
            'standard_name', '', ...
            'units', 'degree', ...
            'FillValue', single(99999), ...
            'long_name', 'Uncalibrated phase shift reported by oxygen sensor', ...
            'valid_min', single(10), ...
            'valid_max', single(70), ...
            'ancillary_variable', 'BPHASE_DOXY_QC', ...
            'sdn_parameter_urn', 'SDN:P01::OXYCPHAB', ...
            'sdn_uom_urn', 'SDN:P06::UAAA', ...
            'sdn_uom_name', '' ...
            );
         
      case 'DPHASE_DOXY'
         o_egoVarStruct = struct( ...
            'ego_variable_name', 'DPHASE_DOXY', ...
            'dim', 'TIME', ...
            'typeof', 'float', ...
            'standard_name', '', ...
            'units', 'degree', ...
            'FillValue', single(99999), ...
            'long_name', 'Calibrated phase shift reported by oxygen sensor', ...
            'valid_min', single(10), ...
            'valid_max', single(70), ...
            'ancillary_variable', 'DPHASE_DOXY_QC', ...
            'sdn_parameter_urn', 'SDN:P01::OXYCPHAC', ...
            'sdn_uom_urn', 'SDN:P06::UAAA', ...
            'sdn_uom_name', '' ...
            );

      case 'TPHASE_DOXY'
         o_egoVarStruct = struct( ...
            'ego_variable_name', 'TPHASE_DOXY', ...
            'dim', 'TIME', ...
            'typeof', 'float', ...
            'standard_name', '', ...
            'units', 'degree', ...
            'FillValue', single(99999), ...
            'long_name', 'Uncalibrated phase shift reported by oxygen sensor', ...
            'valid_min', single(10), ...
            'valid_max', single(70), ...
            'ancillary_variable', 'TPHASE_DOXY_QC', ...
            'sdn_parameter_urn', 'SDN:P01::OXYCPHTC', ...
            'sdn_uom_urn', 'SDN:P06::UAAA', ...
            'sdn_uom_name', '' ...
            );
         
      case 'C1PHASE_DOXY'
         o_egoVarStruct = struct( ...
            'ego_variable_name', 'C1PHASE_DOXY', ...
            'dim', 'TIME', ...
            'typeof', 'float', ...
            'standard_name', '', ...
            'units', 'degree', ...
            'FillValue', single(99999), ...
            'long_name', 'Uncalibrated phase shift reported by oxygen sensor', ...
            'valid_min', single(10), ...
            'valid_max', single(70), ...
            'ancillary_variable', 'C1PHASE_DOXY_QC', ...
            'sdn_parameter_urn', 'SDN:P01::OXYCPHAB', ...
            'sdn_uom_urn', 'SDN:P06::UAAA', ...
            'sdn_uom_name', '' ...
            );         

      case 'C2PHASE_DOXY'
         o_egoVarStruct = struct( ...
            'ego_variable_name', 'C2PHASE_DOXY', ...
            'dim', 'TIME', ...
            'typeof', 'float', ...
            'standard_name', '', ...
            'units', 'degree', ...
            'FillValue', single(99999), ...
            'long_name', 'Uncalibrated phase shift reported by oxygen sensor', ...
            'valid_min', single(0), ...
            'valid_max', single(15), ...
            'ancillary_variable', 'C2PHASE_DOXY_QC', ...
            'sdn_parameter_urn', 'SDN:P01::OXYCPHAR', ...
            'sdn_uom_urn', 'SDN:P06::UAAA', ...
            'sdn_uom_name', '' ...
            );           

      case 'MOLAR_DOXY'
         o_egoVarStruct = struct( ...
            'ego_variable_name', 'MOLAR_DOXY', ...
            'dim', 'TIME', ...
            'typeof', 'float', ...
            'standard_name', 'mole_concentration_of_dissolved_molecular_oxygen_in_sea_water', ...
            'units', 'micromole/l', ...
            'FillValue', single(99999), ...
            'long_name', 'Uncompensated (pressure and salinity) oxygen concentration reported by the oxygen sensor', ...
            'valid_min', single(0), ...
            'valid_max', single(650), ...
            'ancillary_variable', 'MOLAR_DOXY_QC', ...
            'sdn_parameter_urn', 'SDN:P01::DOXYMMOP', ...
            'sdn_uom_urn', 'SDN:P06::MMPL', ...
            'sdn_uom_name', '' ...
            );
         
      case 'PHASE_DELAY_DOXY'
         o_egoVarStruct = struct( ...
            'ego_variable_name', 'PHASE_DELAY_DOXY', ...
            'dim', 'TIME', ...
            'typeof', 'float', ...
            'standard_name', '', ...
            'units', 'microsecond', ...
            'FillValue', single(99999), ...
            'long_name', 'Phase delay reported by oxygen sensor', ...
            'valid_min', single(0), ...
            'valid_max', single(99999), ...
            'ancillary_variable', 'PHASE_DELAY_DOXY_QC', ...
            'sdn_parameter_urn', 'SDN:P01::OXYCPH01', ...
            'sdn_uom_urn', 'SDN:P06::USEC', ...
            'sdn_uom_name', '' ...
            );
         
      case 'MLPL_DOXY'
         o_egoVarStruct = struct( ...
            'ego_variable_name', 'MLPL_DOXY', ...
            'dim', 'TIME', ...
            'typeof', 'float', ...
            'standard_name', '', ...
            'units', 'ml/l', ...
            'FillValue', single(99999), ...
            'long_name', 'Oxygen concentration reported by the oxygen sensor', ...
            'valid_min', single(0), ...
            'valid_max', single(650), ...
            'ancillary_variable', 'MLPL_DOXY_QC', ...
            'sdn_parameter_urn', 'SDN:P01::DOXYZZXX', ...
            'sdn_uom_urn', 'SDN:P06::UMLL', ...
            'sdn_uom_name', '' ...
            );

      case 'NB_SAMPLE'
         o_egoVarStruct = struct( ...
            'ego_variable_name', 'NB_SAMPLE', ...
            'dim', 'TIME', ...
            'typeof', 'float', ...
            'standard_name', '', ...
            'units', 'count', ...
            'FillValue', single(99999), ...
            'long_name', 'Number of samples in bin', ...
            'valid_min', '', ...
            'valid_max', '', ...
            'ancillary_variable', 'NB_SAMPLE_QC', ...
            'sdn_parameter_urn', 'SDN:P01::NUMVALES', ...
            'sdn_uom_urn', 'SDN:P06::UUUU', ...
            'sdn_uom_name', '' ...
            );

      case 'RPHASE_DOXY'
         o_egoVarStruct = struct( ...
            'ego_variable_name', 'RPHASE_DOXY', ...
            'dim', 'TIME', ...
            'typeof', 'float', ...
            'standard_name', '', ...
            'units', 'degree', ...
            'FillValue', single(99999), ...
            'long_name', 'Uncalibrated red phase shift reported by oxygen sensor', ...
            'valid_min', single(10), ...
            'valid_max', single(70), ...
            'ancillary_variable', 'RPHASE_DOXY_QC', ...
            'sdn_parameter_urn', 'SDN:P01::OXYCPHAR', ...
            'sdn_uom_urn', 'SDN:P06::UAAA', ...
            'sdn_uom_name', '' ...
            );
         
      case 'TEMP_COUNT_DOXY'
         o_egoVarStruct = struct( ...
            'ego_variable_name', 'TEMP_COUNT_DOXY', ...
            'dim', 'TIME', ...
            'typeof', 'float', ...
            'standard_name', '', ...
            'units', 'count', ...
            'FillValue', single(99999), ...
            'long_name', 'Count which is expressive of uncalibrated temperature value reported by oxygen sensor', ...
            'valid_min', '', ...
            'valid_max', '', ...
            'ancillary_variable', 'TEMP_COUNT_DOXY_QC', ...
            'sdn_parameter_urn', '', ...
            'sdn_uom_urn', 'SDN:P06::UUUU', ...
            'sdn_uom_name', '' ...
            );

      case 'LED_FLASHING_COUNT_DOXY'
         o_egoVarStruct = struct( ...
            'ego_variable_name', 'LED_FLASHING_COUNT_DOXY', ...
            'dim', 'TIME', ...
            'typeof', 'double', ...
            'standard_name', '', ...
            'units', 'count', ...
            'FillValue', double(99999), ...
            'long_name', 'Number of times oxygen sensor flashing to measure oxygen', ...
            'valid_min', '', ...
            'valid_max', '', ...
            'ancillary_variable', 'LED_FLASHING_COUNT_DOXY_QC', ...
            'sdn_parameter_urn', '', ...
            'sdn_uom_urn', 'SDN:P06::UUUU', ...
            'sdn_uom_name', '' ...
            );         
         
      case 'PPOX_DOXY'
         o_egoVarStruct = struct( ...
            'ego_variable_name', 'PPOX_DOXY', ...
            'dim', 'TIME', ...
            'typeof', 'float', ...
            'standard_name', '', ...
            'units', 'millibar', ...
            'FillValue', single(99999), ...
            'long_name', 'Partial pressure of oxygen', ...
            'valid_min', single(-5), ...
            'valid_max', single(5000), ...
            'ancillary_variable', 'PPOX_DOXY_QC', ...
            'sdn_parameter_urn', 'SDN:P01::PPOXZZ01', ...
            'sdn_uom_urn', 'SDN:P06::UPBB', ...
            'sdn_uom_name', '' ...
            );
         
      case 'BETA_BACKSCATTERING470'
         o_egoVarStruct = struct( ...
            'ego_variable_name', 'BETA_BACKSCATTERING470', ...
            'dim', 'TIME', ...
            'typeof', 'float', ...
            'standard_name', '', ...
            'units', 'count', ...
            'FillValue', single(99999), ...
            'long_name', 'Total angle specific volume from backscattering sensor at 470 nanometers', ...
            'valid_min', '', ...
            'valid_max', '', ...
            'ancillary_variable', 'BETA_BACKSCATTERING470_QC', ...
            'sdn_parameter_urn', 'SDN:P01::NVLTOBS1', ...
            'sdn_uom_urn', 'SDN:P06::UUUU', ...
            'sdn_uom_name', '' ...
            );
         
      case 'BETA_BACKSCATTERING532'
         o_egoVarStruct = struct( ...
            'ego_variable_name', 'BETA_BACKSCATTERING532', ...
            'dim', 'TIME', ...
            'typeof', 'float', ...
            'standard_name', '', ...
            'units', 'count', ...
            'FillValue', single(99999), ...
            'long_name', 'Total angle specific volume from backscattering sensor at 532 nanometers', ...
            'valid_min', '', ...
            'valid_max', '', ...
            'ancillary_variable', 'BETA_BACKSCATTERING532_QC', ...
            'sdn_parameter_urn', 'SDN:P01::NVLTOBS1', ...
            'sdn_uom_urn', 'SDN:P06::UUUU', ...
            'sdn_uom_name', '' ...
            );

      case 'BETA_BACKSCATTERING700'
         o_egoVarStruct = struct( ...
            'ego_variable_name', 'BETA_BACKSCATTERING700', ...
            'dim', 'TIME', ...
            'typeof', 'float', ...
            'standard_name', '', ...
            'units', 'count', ...
            'FillValue', single(99999), ...
            'long_name', 'Total angle specific volume from backscattering sensor at 700 nanometers', ...
            'valid_min', '', ...
            'valid_max', '', ...
            'ancillary_variable', 'BETA_BACKSCATTERING700_QC', ...
            'sdn_parameter_urn', 'SDN:P01::NVLTOBS1', ...
            'sdn_uom_urn', 'SDN:P06::UUUU', ...
            'sdn_uom_name', '' ...
            );

      case 'FLUORESCENCE_CHLA'
         o_egoVarStruct = struct( ...
            'ego_variable_name', 'FLUORESCENCE_CHLA', ...
            'dim', 'TIME', ...
            'typeof', 'float', ...
            'standard_name', '', ...
            'units', 'count', ...
            'FillValue', single(99999), ...
            'long_name', 'Chlorophyll-A signal from fluorescence sensor', ...
            'valid_min', '', ...
            'valid_max', '', ...
            'ancillary_variable', 'FLUORESCENCE_CHLA_QC', ...
            'sdn_parameter_urn', 'SDN:P01::FCNTRW01', ...
            'sdn_uom_urn', 'SDN:P06::UUUU', ...
            'sdn_uom_name', '' ...
            );
         
      case 'FLUORESCENCE_VOLTAGE_CHLA' % for gliders only
         o_egoVarStruct = struct( ...
            'ego_variable_name', 'FLUORESCENCE_VOLTAGE_CHLA', ...
            'dim', 'TIME', ...
            'typeof', 'float', ...
            'standard_name', '', ...
            'units', 'volt', ...
            'FillValue', single(99999), ...
            'long_name', 'Chlorophyll-A signal from analogic fluorescence sensor', ...
            'valid_min', '', ...
            'valid_max', '', ...
            'ancillary_variable', 'FLUORESCENCE_VOLTAGE_CHLA_QC', ...
            'sdn_parameter_urn', '', ...
            'sdn_uom_urn', '', ...
            'sdn_uom_name', '' ...
            );

      case 'TEMP_CPU_CHLA'
         o_egoVarStruct = struct( ...
            'ego_variable_name', 'TEMP_CPU_CHLA', ...
            'dim', 'TIME', ...
            'typeof', 'float', ...
            'standard_name', '', ...
            'units', 'count', ...
            'FillValue', single(99999), ...
            'long_name', 'Thermistor signal from backscattering sensor', ...
            'valid_min', '', ...
            'valid_max', '', ...
            'ancillary_variable', 'TEMP_CPU_CHLA_QC', ...
            'sdn_parameter_urn', 'SDN:P01::TCNTICPU', ...
            'sdn_uom_urn', 'SDN:P06::UUUU', ...
            'sdn_uom_name', '' ...
            );
         
      case 'FLUORESCENCE_CDOM'
         o_egoVarStruct = struct( ...
            'ego_variable_name', 'FLUORESCENCE_CDOM', ...
            'dim', 'TIME', ...
            'typeof', 'float', ...
            'standard_name', '', ...
            'units', 'count', ...
            'FillValue', single(99999), ...
            'long_name', 'Raw fluorescence from coloured dissolved organic matter sensor', ...
            'valid_min', '', ...
            'valid_max', '', ...
            'ancillary_variable', 'FLUORESCENCE_CDOM_QC', ...
            'sdn_parameter_urn', 'SDN:P01::FLUOCDOM', ...
            'sdn_uom_urn', 'SDN:P06::UUUU', ...
            'sdn_uom_name', '' ...
            );
         
      case 'SIDE_SCATTERING_TURBIDITY'
         o_egoVarStruct = struct( ...
            'ego_variable_name', 'SIDE_SCATTERING_TURBIDITY', ...
            'dim', 'TIME', ...
            'typeof', 'float', ...
            'standard_name', '', ...
            'units', 'count', ...
            'FillValue', single(99999), ...
            'long_name', 'Turbidity signal from side scattering sensor', ...
            'valid_min', '', ...
            'valid_max', '', ...
            'ancillary_variable', 'SIDE_SCATTERING_TURBIDITY_QC', ...
            'sdn_parameter_urn', 'SDN:P01::NCNTTUR1', ...
            'sdn_uom_urn', 'SDN:P06::UUUU', ...
            'sdn_uom_name', '' ...
            );
         
      case 'TRANSMITTANCE_PARTICLE_BEAM_ATTENUATION660'
         o_egoVarStruct = struct( ...
            'ego_variable_name', 'TRANSMITTANCE_PARTICLE_BEAM_ATTENUATION660', ...
            'dim', 'TIME', ...
            'typeof', 'float', ...
            'standard_name', '', ...
            'units', 'count', ...
            'FillValue', single(99999), ...
            'long_name', 'Beam attenuation from transmissometer sensor at 660 nanometers', ...
            'valid_min', '', ...
            'valid_max', '', ...
            'ancillary_variable', 'TRANSMITTANCE_PARTICLE_BEAM_ATTENUATION660_QC', ...
            'sdn_parameter_urn', 'SDN:P01::NCNTATT1', ...
            'sdn_uom_urn', 'SDN:P06::UUUU', ...
            'sdn_uom_name', '' ...
            );
         
      case 'UV_INTENSITY_NITRATE'
         o_egoVarStruct = struct( ...
            'ego_variable_name', 'UV_INTENSITY_NITRATE', ...
            'dim', 'TIME', ...
            'typeof', 'float', ...
            'standard_name', '', ...
            'units', 'count', ...
            'FillValue', single(99999), ...
            'long_name', 'Intensity of ultra violet flux from nitrate sensor', ...
            'valid_min', '', ...
            'valid_max', '', ...
            'ancillary_variable', 'UV_INTENSITY_NITRATE_QC', ...
            'sdn_parameter_urn', 'SDN:P01::UVINZZ01', ...
            'sdn_uom_urn', 'SDN:P06::UUUU', ...
            'sdn_uom_name', '' ...
            );

      case 'UV_INTENSITY_DARK_NITRATE'
         o_egoVarStruct = struct( ...
            'ego_variable_name', 'UV_INTENSITY_DARK_NITRATE', ...
            'dim', 'TIME', ...
            'typeof', 'float', ...
            'standard_name', '', ...
            'units', 'count', ...
            'FillValue', single(99999), ...
            'long_name', 'Intensity of ultra violet flux dark measurement from nitrate sensor', ...
            'valid_min', '', ...
            'valid_max', '', ...
            'ancillary_variable', 'UV_INTENSITY_DARK_NITRATE_QC', ...
            'sdn_parameter_urn', 'SDN:P01::UVDAZZ01', ...
            'sdn_uom_urn', 'SDN:P06::UUUU', ...
            'sdn_uom_name', '' ...
            );
         
      case 'UV_INTENSITY_DARK_SEAWATER_NITRATE'
         o_egoVarStruct = struct( ...
            'ego_variable_name', 'UV_INTENSITY_DARK_SEAWATER_NITRATE', ...
            'dim', 'TIME', ...
            'typeof', 'float', ...
            'standard_name', '', ...
            'units', 'count', ...
            'FillValue', single(99999), ...
            'long_name', 'Intensity of ultra-violet flux dark sea water from nitrate sensor', ...
            'valid_min', '', ...
            'valid_max', '', ...
            'ancillary_variable', 'UV_INTENSITY_DARK_SEAWATER_NITRATE_QC', ...
            'sdn_parameter_urn', 'SDN:P01::UVSDZZ01', ...
            'sdn_uom_urn', 'SDN:P06::UUUU', ...
            'sdn_uom_name', '' ...
            );
         
      case 'MOLAR_NITRATE'
         o_egoVarStruct = struct( ...
            'ego_variable_name', 'MOLAR_NITRATE', ...
            'dim', 'TIME', ...
            'typeof', 'float', ...
            'standard_name', '', ...
            'units', 'micromole/l', ...
            'FillValue', single(99999), ...
            'long_name', 'Nitrate', ...
            'valid_min', '', ...
            'valid_max', '', ...
            'ancillary_variable', 'MOLAR_NITRATE_QC', ...
            'sdn_parameter_urn', 'SDN:P01::NTRZMC01', ...
            'sdn_uom_urn', 'SDN:P06::UPOX', ...
            'sdn_uom_name', '' ...
            );
         
      case 'FIT_ERROR_NITRATE'
         o_egoVarStruct = struct( ...
            'ego_variable_name', 'FIT_ERROR_NITRATE', ...
            'dim', 'TIME', ...
            'typeof', 'float', ...
            'standard_name', '', ...
            'units', 'dimensionless', ...
            'FillValue', single(99999), ...
            'long_name', 'Nitrate fit error', ...
            'valid_min', '', ...
            'valid_max', '', ...
            'ancillary_variable', 'FIT_ERROR_NITRATE_QC', ...
            'sdn_parameter_urn', 'SDN:P01::NTFEZZ01', ...
            'sdn_uom_urn', 'SDN:P06::UUUU', ...
            'sdn_uom_name', '' ...
            );

      case 'TEMP_NITRATE'
         o_egoVarStruct = struct( ...
            'ego_variable_name', 'TEMP_NITRATE', ...
            'dim', 'TIME', ...
            'typeof', 'float', ...
            'standard_name', '', ...
            'units', 'degree_Celsius', ...
            'FillValue', single(99999), ...
            'long_name', 'Internal temperature of the SUNA sensor', ...
            'valid_min', '', ...
            'valid_max', '', ...
            'ancillary_variable', 'TEMP_NITRATE_QC', ...
            'sdn_parameter_urn', '', ...
            'sdn_uom_urn', '', ...
            'sdn_uom_name', '' ...
            );
         
      case 'TEMP_SPECTROPHOTOMETER_NITRATE'
         o_egoVarStruct = struct( ...
            'ego_variable_name', 'TEMP_SPECTROPHOTOMETER_NITRATE', ...
            'dim', 'TIME', ...
            'typeof', 'float', ...
            'standard_name', '', ...
            'units', 'degree_Celsius', ...
            'FillValue', single(99999), ...
            'long_name', 'Temperature of the spectrometer', ...
            'valid_min', '', ...
            'valid_max', '', ...
            'ancillary_variable', 'TEMP_SPECTROPHOTOMETER_NITRATE_QC', ...
            'sdn_parameter_urn', '', ...
            'sdn_uom_urn', '', ...
            'sdn_uom_name', '' ...
            );
         
      case 'HUMIDITY_NITRATE'
         o_egoVarStruct = struct( ...
            'ego_variable_name', 'HUMIDITY_NITRATE', ...
            'dim', 'TIME', ...
            'typeof', 'float', ...
            'standard_name', '', ...
            'units', 'percent', ...
            'FillValue', single(99999), ...
            'long_name', 'Relative humidity inside the SUNA sensor (If > 50% There is a leak)', ...
            'valid_min', single(0), ...
            'valid_max', single(100), ...
            'ancillary_variable', 'HUMIDITY_NITRATE_QC', ...
            'sdn_parameter_urn', '', ...
            'sdn_uom_urn', '', ...
            'sdn_uom_name', '' ...
            );
         
      case 'VRS_PH'
         o_egoVarStruct = struct( ...
            'ego_variable_name', 'VRS_PH', ...
            'dim', 'TIME', ...
            'typeof', 'float', ...
            'standard_name', '', ...
            'units', 'volt', ...
            'FillValue', single(99999), ...
            'long_name', 'Voltage difference between reference and source from pH sensor', ...
            'valid_min', '', ...
            'valid_max', '', ...
            'ancillary_variable', 'VRS_PH_QC', ...
            'sdn_parameter_urn', 'SDN:P01::PVLTGC01', ...
            'sdn_uom_urn', 'SDN:P06::UVLT', ...
            'sdn_uom_name', '' ...
            );
         
      case 'TEMP_PH'
         o_egoVarStruct = struct( ...
            'ego_variable_name', 'TEMP_PH', ...
            'dim', 'TIME', ...
            'typeof', 'float', ...
            'standard_name', '', ...
            'units', 'degree_Celsius', ...
            'FillValue', single(99999), ...
            'long_name', 'Sea temperature from pH sensor', ...
            'valid_min', single(-2), ...
            'valid_max', single(40), ...
            'ancillary_variable', 'TEMP_PH_QC', ...
            'sdn_parameter_urn', '', ...
            'sdn_uom_urn', '', ...
            'sdn_uom_name', '' ...
            );         
         
      case 'IB_PH'
         o_egoVarStruct = struct( ...
            'ego_variable_name', 'IB_PH', ...
            'dim', 'TIME', ...
            'typeof', 'float', ...
            'standard_name', '', ...
            'units', 'nanoampere', ...
            'FillValue', single(99999), ...
            'long_name', 'Base current of pH sensor', ...
            'valid_min', '', ...
            'valid_max', '', ...
            'ancillary_variable', 'IB_PH_QC', ...
            'sdn_parameter_urn', '', ...
            'sdn_uom_urn', '', ...
            'sdn_uom_name', '' ...
            );
         
      case 'VK_PH'
         o_egoVarStruct = struct( ...
            'ego_variable_name', 'VK_PH', ...
            'dim', 'TIME', ...
            'typeof', 'float', ...
            'standard_name', '', ...
            'units', 'volt', ...
            'FillValue', single(99999), ...
            'long_name', 'Counter electrode voltage of pH sensor', ...
            'valid_min', '', ...
            'valid_max', '', ...
            'ancillary_variable', 'VK_PH_QC', ...
            'sdn_parameter_urn', '', ...
            'sdn_uom_urn', '', ...
            'sdn_uom_name', '' ...
            );
         
      case 'IK_PH'
         o_egoVarStruct = struct( ...
            'ego_variable_name', 'IK_PH', ...
            'dim', 'TIME', ...
            'typeof', 'float', ...
            'standard_name', '', ...
            'units', 'nanoampere', ...
            'FillValue', single(99999), ...
            'long_name', 'Counter electrode current of pH sensor', ...
            'valid_min', '', ...
            'valid_max', '', ...
            'ancillary_variable', 'IK_PH_QC', ...
            'sdn_parameter_urn', '', ...
            'sdn_uom_urn', '', ...
            'sdn_uom_name', '' ...
            );
         
      case 'PH_IN_SITU_FREE'
         o_egoVarStruct = struct( ...
            'ego_variable_name', 'PH_IN_SITU_FREE', ...
            'dim', 'TIME', ...
            'typeof', 'float', ...
            'standard_name', '', ...
            'units', 'dimensionless', ...
            'FillValue', single(99999), ...
            'long_name', 'pH', ...
            'valid_min', '', ...
            'valid_max', '', ...
            'ancillary_variable', 'PH_IN_SITU_FREE_QC', ...
            'sdn_parameter_urn', 'SDN:P01::PHFRWCAL', ...
            'sdn_uom_urn', 'SDN:P06::UUPH', ...
            'sdn_uom_name', '' ...
            );

      case 'PH_IN_SITU_SEAWATER'
         o_egoVarStruct = struct( ...
            'ego_variable_name', 'PH_IN_SITU_SEAWATER', ...
            'dim', 'TIME', ...
            'typeof', 'float', ...
            'standard_name', '', ...
            'units', 'dimensionless', ...
            'FillValue', single(99999), ...
            'long_name', 'pH', ...
            'valid_min', '', ...
            'valid_max', '', ...
            'ancillary_variable', 'PH_IN_SITU_SEAWATER_QC', ...
            'sdn_parameter_urn', 'SDN:P01::PHSWWCAL', ...
            'sdn_uom_urn', 'SDN:P06::UUPH', ...
            'sdn_uom_name', '' ...
            );
         
      case 'RAW_DOWNWELLING_IRRADIANCE380'
         o_egoVarStruct = struct( ...
            'ego_variable_name', 'RAW_DOWNWELLING_IRRADIANCE380', ...
            'dim', 'TIME', ...
            'typeof', 'float', ...
            'standard_name', '', ...
            'units', 'count', ...
            'FillValue', single(99999), ...
            'long_name', 'Raw downwelling irradiance at 380 nanometers', ...
            'valid_min', '', ...
            'valid_max', '', ...
            'ancillary_variable', 'RAW_DOWNWELLING_IRRADIANCE380_QC', ...
            'sdn_parameter_urn', 'SDN:P01::DWIRXXZZ', ...
            'sdn_uom_urn', 'SDN:P06::UUUU', ...
            'sdn_uom_name', '' ...
            );
         
      case 'RAW_DOWNWELLING_IRRADIANCE412'
         o_egoVarStruct = struct( ...
            'ego_variable_name', 'RAW_DOWNWELLING_IRRADIANCE412', ...
            'dim', 'TIME', ...
            'typeof', 'float', ...
            'standard_name', '', ...
            'units', 'count', ...
            'FillValue', single(99999), ...
            'long_name', 'Raw downwelling irradiance at 412 nanometers', ...
            'valid_min', '', ...
            'valid_max', '', ...
            'ancillary_variable', 'RAW_DOWNWELLING_IRRADIANCE412_QC', ...
            'sdn_parameter_urn', 'SDN:P01::DWIRXXZZ', ...
            'sdn_uom_urn', 'SDN:P06::UUUU', ...
            'sdn_uom_name', '' ...
            );
         
      case 'RAW_DOWNWELLING_IRRADIANCE443'
         o_egoVarStruct = struct( ...
            'ego_variable_name', 'RAW_DOWNWELLING_IRRADIANCE443', ...
            'dim', 'TIME', ...
            'typeof', 'float', ...
            'standard_name', '', ...
            'units', 'count', ...
            'FillValue', single(99999), ...
            'long_name', 'Raw downwelling irradiance at 443 nanometers', ...
            'valid_min', '', ...
            'valid_max', '', ...
            'ancillary_variable', 'RAW_DOWNWELLING_IRRADIANCE443_QC', ...
            'sdn_parameter_urn', 'SDN:P01::DWIRXXZZ', ...
            'sdn_uom_urn', 'SDN:P06::UUUU', ...
            'sdn_uom_name', '' ...
            );
         
      case 'RAW_DOWNWELLING_IRRADIANCE490'
         o_egoVarStruct = struct( ...
            'ego_variable_name', 'RAW_DOWNWELLING_IRRADIANCE490', ...
            'dim', 'TIME', ...
            'typeof', 'float', ...
            'standard_name', '', ...
            'units', 'count', ...
            'FillValue', single(99999), ...
            'long_name', 'Raw downwelling irradiance at 490 nanometers', ...
            'valid_min', '', ...
            'valid_max', '', ...
            'ancillary_variable', 'RAW_DOWNWELLING_IRRADIANCE490_QC', ...
            'sdn_parameter_urn', 'SDN:P01::DWIRXXZZ', ...
            'sdn_uom_urn', 'SDN:P06::UUUU', ...
            'sdn_uom_name', '' ...
            );
         
      case 'RAW_DOWNWELLING_IRRADIANCE555'
         o_egoVarStruct = struct( ...
            'ego_variable_name', 'RAW_DOWNWELLING_IRRADIANCE555', ...
            'dim', 'TIME', ...
            'typeof', 'float', ...
            'standard_name', '', ...
            'units', 'count', ...
            'FillValue', single(99999), ...
            'long_name', 'Raw downwelling irradiance at 555 nanometers', ...
            'valid_min', '', ...
            'valid_max', '', ...
            'ancillary_variable', 'RAW_DOWNWELLING_IRRADIANCE555_QC', ...
            'sdn_parameter_urn', 'SDN:P01::DWIRXXZZ', ...
            'sdn_uom_urn', 'SDN:P06::UUUU', ...
            'sdn_uom_name', '' ...
            );
         
      case 'RAW_UPWELLING_RADIANCE412'
         o_egoVarStruct = struct( ...
            'ego_variable_name', 'RAW_UPWELLING_RADIANCE412', ...
            'dim', 'TIME', ...
            'typeof', 'float', ...
            'standard_name', '', ...
            'units', 'count', ...
            'FillValue', single(99999), ...
            'long_name', 'Raw upwelling radiance at 412 nanometers', ...
            'valid_min', '', ...
            'valid_max', '', ...
            'ancillary_variable', 'RAW_UPWELLING_RADIANCE412_QC', ...
            'sdn_parameter_urn', 'SDN:P01::UPRAXXZZ', ...
            'sdn_uom_urn', 'SDN:P06::UUUU', ...
            'sdn_uom_name', '' ...
            );
         
      case 'RAW_UPWELLING_RADIANCE443'
         o_egoVarStruct = struct( ...
            'ego_variable_name', 'RAW_UPWELLING_RADIANCE443', ...
            'dim', 'TIME', ...
            'typeof', 'float', ...
            'standard_name', '', ...
            'units', 'count', ...
            'FillValue', single(99999), ...
            'long_name', 'Raw upwelling radiance at 443 nanometers', ...
            'valid_min', '', ...
            'valid_max', '', ...
            'ancillary_variable', 'RAW_UPWELLING_RADIANCE443_QC', ...
            'sdn_parameter_urn', 'SDN:P01::UPRAXXZZ', ...
            'sdn_uom_urn', 'SDN:P06::UUUU', ...
            'sdn_uom_name', '' ...
            );
         
      case 'RAW_UPWELLING_RADIANCE490'
         o_egoVarStruct = struct( ...
            'ego_variable_name', 'RAW_UPWELLING_RADIANCE490', ...
            'dim', 'TIME', ...
            'typeof', 'float', ...
            'standard_name', '', ...
            'units', 'count', ...
            'FillValue', single(99999), ...
            'long_name', 'Raw upwelling radiance at 490 nanometers', ...
            'valid_min', '', ...
            'valid_max', '', ...
            'ancillary_variable', 'RAW_UPWELLING_RADIANCE490_QC', ...
            'sdn_parameter_urn', 'SDN:P01::UPRAXXZZ', ...
            'sdn_uom_urn', 'SDN:P06::UUUU', ...
            'sdn_uom_name', '' ...
            );
         
      case 'RAW_UPWELLING_RADIANCE555'
         o_egoVarStruct = struct( ...
            'ego_variable_name', 'RAW_UPWELLING_RADIANCE555', ...
            'dim', 'TIME', ...
            'typeof', 'float', ...
            'standard_name', '', ...
            'units', 'count', ...
            'FillValue', single(99999), ...
            'long_name', 'Raw upwelling radiance at 555 nanometers', ...
            'valid_min', '', ...
            'valid_max', '', ...
            'ancillary_variable', 'RAW_UPWELLING_RADIANCE555_QC', ...
            'sdn_parameter_urn', 'SDN:P01::UPRAXXZZ', ...
            'sdn_uom_urn', 'SDN:P06::UUUU', ...
            'sdn_uom_name', '' ...
            );
         
      case 'RAW_DOWNWELLING_PAR'
         o_egoVarStruct = struct( ...
            'ego_variable_name', 'RAW_DOWNWELLING_PAR', ...
            'dim', 'TIME', ...
            'typeof', 'float', ...
            'standard_name', '', ...
            'units', 'count', ...
            'FillValue', single(99999), ...
            'long_name', 'Raw downwelling photosynthetic available radiation', ...
            'valid_min', '', ...
            'valid_max', '', ...
            'ancillary_variable', 'RAW_DOWNWELLING_PAR_QC', ...
            'sdn_parameter_urn', 'SDN:P01::DWIRRXZZ', ...
            'sdn_uom_urn', 'SDN:P06::UUUU', ...
            'sdn_uom_name', '' ...
            );

      case 'FLUORESCENCE_URANINE'
         o_egoVarStruct = struct( ...
            'ego_variable_name', 'FLUORESCENCE_URANINE', ...
            'dim', 'TIME', ...
            'typeof', 'float', ...
            'standard_name', '', ...
            'units', 'count', ...
            'FillValue', single(99999), ...
            'long_name', 'Uranine signal from fluorescence sensor', ...
            'valid_min', '', ...
            'valid_max', '', ...
            'ancillary_variable', 'FLUORESCENCE_URANINE_QC', ...
            'sdn_parameter_urn', '', ...
            'sdn_uom_urn', '', ...
            'sdn_uom_name', '' ...
            );

      case 'FLUORESCENCE_RHODAMINE'
         o_egoVarStruct = struct( ...
            'ego_variable_name', 'FLUORESCENCE_RHODAMINE', ...
            'dim', 'TIME', ...
            'typeof', 'float', ...
            'standard_name', '', ...
            'units', 'count', ...
            'FillValue', single(99999), ...
            'long_name', 'Rhodamine signal from fluorescence sensor', ...
            'valid_min', '', ...
            'valid_max', '', ...
            'ancillary_variable', 'FLUORESCENCE_RHODAMINE_QC', ...
            'sdn_parameter_urn', '', ...
            'sdn_uom_urn', '', ...
            'sdn_uom_name', '' ...
            );

      otherwise
         if (again == 1)
            if (isletter(a_egoVarName(end-1)) && ~isletter(a_egoVarName(end)))
               egoVarName = a_egoVarName(1:end-1);
               again = 2;
            elseif ((a_egoVarName(end-1) == '_') && ~isletter(a_egoVarName(end)))
               egoVarName = a_egoVarName(1:end-2);
               again = 3;
            else
               fprintf('WARNING: EGO variable attributes no yet defined for EGO variable %s\n', a_egoVarName);
               again = 0;
            end
         else
            fprintf('WARNING: EGO variable attributes no yet defined for EGO variable %s\n', a_egoVarName);
            again = 0;
         end
   end
   if (~isempty(o_egoVarStruct))
      if ((again == 2) || (again == 3))
         o_egoVarStruct.ego_variable_name = a_egoVarName;
         o_egoVarStruct.ancillary_variable = [a_egoVarName '_QC'];
      end
      again = 0;
   end
end

return
