% ------------------------------------------------------------------------------
% Create a KML location.
%
% SYNTAX :
%   [o_kmlStr] = ge_create_pos(a_lon, a_lat, a_description, a_name, a_style,
%                              a_timeSpanStart, a_timeSpanEnd)
%
% INPUT PARAMETERS :
%   a_lon, a_lat    : longitude and latitude of the location
%   a_description   : description of the location
%   a_name          : name of the location
%   a_style         : style of the location
%   a_timeSpanStart : time span start of the location
%   a_timeSpanEnd   : time span end of the location
%
% OUTPUT PARAMETERS :
%   o_kmlStr : KML code of the location
%
% EXAMPLES :
%
% SEE ALSO : 
% AUTHORS  : Jean-Philippe Rannou (Altran)(jean-philippe.rannou@altran.com)
% ------------------------------------------------------------------------------
% RELEASES :
%   04/19/2015 - RNU - creation
% ------------------------------------------------------------------------------
function [o_kmlStr] = ge_create_pos(a_lon, a_lat, a_description, a_name, ...
   a_style, a_timeSpanStart, a_timeSpanEnd)

o_kmlStr = [];

timeSpanStartStr = [];
timeSpanEndStr = [];
if (~isempty(a_timeSpanStart))
   timeSpanStartStr = [ ...
      9, 9, 9, 9, '<begin>', a_timeSpanStart, '</begin>', 10, ...
      ];
end
if (~isempty(a_timeSpanEnd))
   timeSpanEndStr = [ ...
      9, 9, 9, 9, '<end>', a_timeSpanEnd, '</end>', 10, ...
      ];
end
timeSpanStr = [ ...
   9, 9, 9, '<TimeSpan>', 10, ...
   timeSpanStartStr, ...
   timeSpanEndStr, ...
   9, 9, 9, '</TimeSpan>', 10, ...
   ];

description = [];
if (~isempty(a_description))
   description = [ ...
      9, 9, 9, '<description>', 10, ...
      9, 9, 9, 9, '<![CDATA[' a_description ']]>', 10, ...
      9, 9, 9, '</description>', 10, ...
      ];
end

name = [];
if (~isempty(a_name))
   name = [ ...
      9, 9, 9, '<name>', a_name, '</name>', 10, ...
      ];
end

coordinatesLine = [];
for idPos = 1:length(a_lon)
   coordinatesLine = [ coordinatesLine...
      sprintf('%.3f,%.3f,0 ', a_lon(idPos), a_lat(idPos))];
end

o_kmlStr = [ ...
   9, 9, '<Placemark>', 10, ...
   9, 9, 9, '<visibility> 0 </visibility>', 10, ...
   description, ...
   name, ...
   9, 9, 9, '<styleUrl>', a_style, '</styleUrl>', 10, ...
   timeSpanStr, ...
   9, 9, 9, '<Point>', 10, ...
   9, 9, 9, 9, '<coordinates>', 10, ...
   9, 9, 9, 9, 9, coordinatesLine, 10, ...
   9, 9, 9, 9, '</coordinates>', 10, ...
   9, 9, 9, '</Point>', 10, ...
   9, 9, '</Placemark>', 10, ...
   ];

return
