% ------------------------------------------------------------------------------
% Create a KML line.
%
% SYNTAX :
%  [o_kmlStr] = ge_create_line(a_lon, a_lat, a_juld, a_style)
%
% INPUT PARAMETERS :
%   a_lon, a_lat : longitude and latitude of the line
%   a_juld       : date of the line
%   a_style      : style of the line
%
% OUTPUT PARAMETERS :
%   o_kmlStr : KML code of the line
%
% EXAMPLES :
%
% SEE ALSO : 
% AUTHORS  : Jean-Philippe Rannou (Altran)(jean-philippe.rannou@altran.com)
% ------------------------------------------------------------------------------
% RELEASES :
%   04/19/2015 - RNU - creation
% ------------------------------------------------------------------------------
function [o_kmlStr] = ge_create_line(a_lon, a_lat, a_juld, a_style)

o_kmlStr = [];

o_kmlStr = [o_kmlStr ...
   9, 9, '<Placemark>', 10, ...
   9, 9, 9, '<styleUrl>', a_style, '</styleUrl>', 10, ...
   9, 9, 9, '<TimeSpan>', 10, ...
   9, 9, 9, 9, '<begin>', datestr(a_juld(1), 'yyyy-mm-ddTHH:MM:SSZ'), '</begin>', 10, ...
   9, 9, 9, '</TimeSpan>', 10, ...
   9, 9, 9, '<LineString>', 10, ...
   9, 9, 9, 9, '<coordinates>', 10, ...
   9, 9, 9, 9, 9, sprintf('%.3f,%.3f,0 ', a_lon(1), a_lat(1)), 10, ...
   9, 9, 9, 9, '</coordinates>', 10, ...
   9, 9, 9, '</LineString>', 10, ...
   9, 9, '</Placemark>', 10, ...
   ];

for idPos = 2:length(a_juld)
   o_kmlStr = [o_kmlStr ...
      9, 9, '<Placemark>', 10, ...
      9, 9, 9, '<styleUrl>', a_style, '</styleUrl>', 10, ...
      9, 9, 9, '<TimeSpan>', 10, ...
      9, 9, 9, 9, '<begin>', datestr(a_juld(idPos), 'yyyy-mm-ddTHH:MM:SSZ'), '</begin>', 10, ...
      9, 9, 9, '</TimeSpan>', 10, ...
      9, 9, 9, '<LineString>', 10, ...
      9, 9, 9, 9, '<coordinates>', 10, ...
      9, 9, 9, 9, 9, [sprintf('%.3f,%.3f,0 ', a_lon(idPos-1), a_lat(idPos-1)) sprintf('%.3f,%.3f,0 ', a_lon(idPos), a_lat(idPos))], 10, ...
      9, 9, 9, 9, '</coordinates>', 10, ...
      9, 9, 9, '</LineString>', 10, ...
      9, 9, '</Placemark>', 10, ...
      ];
end

return
